# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1441/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1441/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/serafm/dev/rtree_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/serafm/dev/rtree_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1441/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1441/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/serafm/dev/rtree_cpp/CMakeFiles /home/serafm/dev/rtree_cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/serafm/dev/rtree_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rtree_cpp

# Build rule for target.
rtree_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtree_cpp
.PHONY : rtree_cpp

# fast build rule for target.
rtree_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/build
.PHONY : rtree_cpp/fast

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/rtree/builders/QueryBuilder.o: src/rtree/builders/QueryBuilder.cpp.o
.PHONY : src/rtree/builders/QueryBuilder.o

# target to build an object file
src/rtree/builders/QueryBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/builders/QueryBuilder.cpp.o
.PHONY : src/rtree/builders/QueryBuilder.cpp.o

src/rtree/builders/QueryBuilder.i: src/rtree/builders/QueryBuilder.cpp.i
.PHONY : src/rtree/builders/QueryBuilder.i

# target to preprocess a source file
src/rtree/builders/QueryBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/builders/QueryBuilder.cpp.i
.PHONY : src/rtree/builders/QueryBuilder.cpp.i

src/rtree/builders/QueryBuilder.s: src/rtree/builders/QueryBuilder.cpp.s
.PHONY : src/rtree/builders/QueryBuilder.s

# target to generate assembly for a file
src/rtree/builders/QueryBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/builders/QueryBuilder.cpp.s
.PHONY : src/rtree/builders/QueryBuilder.cpp.s

src/rtree/builders/RTreeBulkLoad.o: src/rtree/builders/RTreeBulkLoad.cpp.o
.PHONY : src/rtree/builders/RTreeBulkLoad.o

# target to build an object file
src/rtree/builders/RTreeBulkLoad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/builders/RTreeBulkLoad.cpp.o
.PHONY : src/rtree/builders/RTreeBulkLoad.cpp.o

src/rtree/builders/RTreeBulkLoad.i: src/rtree/builders/RTreeBulkLoad.cpp.i
.PHONY : src/rtree/builders/RTreeBulkLoad.i

# target to preprocess a source file
src/rtree/builders/RTreeBulkLoad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/builders/RTreeBulkLoad.cpp.i
.PHONY : src/rtree/builders/RTreeBulkLoad.cpp.i

src/rtree/builders/RTreeBulkLoad.s: src/rtree/builders/RTreeBulkLoad.cpp.s
.PHONY : src/rtree/builders/RTreeBulkLoad.s

# target to generate assembly for a file
src/rtree/builders/RTreeBulkLoad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/builders/RTreeBulkLoad.cpp.s
.PHONY : src/rtree/builders/RTreeBulkLoad.cpp.s

src/rtree/structures/Node.o: src/rtree/structures/Node.cpp.o
.PHONY : src/rtree/structures/Node.o

# target to build an object file
src/rtree/structures/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/structures/Node.cpp.o
.PHONY : src/rtree/structures/Node.cpp.o

src/rtree/structures/Node.i: src/rtree/structures/Node.cpp.i
.PHONY : src/rtree/structures/Node.i

# target to preprocess a source file
src/rtree/structures/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/structures/Node.cpp.i
.PHONY : src/rtree/structures/Node.cpp.i

src/rtree/structures/Node.s: src/rtree/structures/Node.cpp.s
.PHONY : src/rtree/structures/Node.s

# target to generate assembly for a file
src/rtree/structures/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/structures/Node.cpp.s
.PHONY : src/rtree/structures/Node.cpp.s

src/rtree/structures/Point.o: src/rtree/structures/Point.cpp.o
.PHONY : src/rtree/structures/Point.o

# target to build an object file
src/rtree/structures/Point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/structures/Point.cpp.o
.PHONY : src/rtree/structures/Point.cpp.o

src/rtree/structures/Point.i: src/rtree/structures/Point.cpp.i
.PHONY : src/rtree/structures/Point.i

# target to preprocess a source file
src/rtree/structures/Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/structures/Point.cpp.i
.PHONY : src/rtree/structures/Point.cpp.i

src/rtree/structures/Point.s: src/rtree/structures/Point.cpp.s
.PHONY : src/rtree/structures/Point.s

# target to generate assembly for a file
src/rtree/structures/Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/structures/Point.cpp.s
.PHONY : src/rtree/structures/Point.cpp.s

src/rtree/structures/Rectangle.o: src/rtree/structures/Rectangle.cpp.o
.PHONY : src/rtree/structures/Rectangle.o

# target to build an object file
src/rtree/structures/Rectangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/structures/Rectangle.cpp.o
.PHONY : src/rtree/structures/Rectangle.cpp.o

src/rtree/structures/Rectangle.i: src/rtree/structures/Rectangle.cpp.i
.PHONY : src/rtree/structures/Rectangle.i

# target to preprocess a source file
src/rtree/structures/Rectangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/structures/Rectangle.cpp.i
.PHONY : src/rtree/structures/Rectangle.cpp.i

src/rtree/structures/Rectangle.s: src/rtree/structures/Rectangle.cpp.s
.PHONY : src/rtree/structures/Rectangle.s

# target to generate assembly for a file
src/rtree/structures/Rectangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtree_cpp.dir/build.make CMakeFiles/rtree_cpp.dir/src/rtree/structures/Rectangle.cpp.s
.PHONY : src/rtree/structures/Rectangle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rtree_cpp"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/rtree/builders/QueryBuilder.o"
	@echo "... src/rtree/builders/QueryBuilder.i"
	@echo "... src/rtree/builders/QueryBuilder.s"
	@echo "... src/rtree/builders/RTreeBulkLoad.o"
	@echo "... src/rtree/builders/RTreeBulkLoad.i"
	@echo "... src/rtree/builders/RTreeBulkLoad.s"
	@echo "... src/rtree/structures/Node.o"
	@echo "... src/rtree/structures/Node.i"
	@echo "... src/rtree/structures/Node.s"
	@echo "... src/rtree/structures/Point.o"
	@echo "... src/rtree/structures/Point.i"
	@echo "... src/rtree/structures/Point.s"
	@echo "... src/rtree/structures/Rectangle.o"
	@echo "... src/rtree/structures/Rectangle.i"
	@echo "... src/rtree/structures/Rectangle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

